# Site settings
title: OfferPad Style Guide
email: your-email@example.com
description: OfferPad Style Guiide and Pattern Library
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
styles: /css/styles.css

# Processing settings
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title
destination: _site
sass:
    sass_dir: _scss
    #style: :compressed
collections:
    docs:
        output: true
        permalink: /:path
defaults:
    -
        scope:
            path: "_docs"
        values:
            layout: default
            type: doc
    -
        scope:
            path: "_docs/get-started"
        values:
            type: "get-started"
    -
        scope:
            path: "_docs/base"
        values:
            type: "base"

# Plugins
plugins:
- jekyll-autoprefixer

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .editorconfig
  - .gitignore
