# Site settings
title: OfferPad Style Guide
email: your-email@example.com
description: OfferPad Style Guide and Pattern Library
baseurl: /Floorplan
url: "" # the base hostname & protocol for your site, e.g. http://example.com
styles: /assets/css/styles.css
images: /assets/images

# Processing settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
destination: _site
incremental: true
sass:
    sass_dir: _scss
    #style: :compressed
collections:
    docs:
        output: true
        permalink: /:path
    examples:
        output: true
        permalink: /examples/:path
defaults:
    -
        scope:
            path: "_docs"
        values:
            layout: default
            type: doc
    -
        scope:
            path: "_docs/get-started"
        values:
            type: "get-started"
    -
        scope:
            path: "_docs/base"
        values:
            type: "base"
    -
        scope:
            path: "_docs/elements"
        values:
            type: "elements"
    -
        scope:
            path: "_docs/patterns"
        values:
            type: "patterns"
    -
        scope:
            path: "_examples"
        values:
            layout: example
            type: "examples"

# Plugins
plugins:
- jekyll-autoprefixer

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .editorconfig
  - .gitignore
